export const cities = [
    { title: 'New York', country: 'United States' },
    { title: 'Los Angeles', country: 'United States' },
    { title: 'Chicago', country: 'United States' },
    { title: 'Houston', country: 'United States' },
    { title: 'Phoenix', country: 'United States' },
    { title: 'Toronto', country: 'Canada' },
    { title: 'Vancouver', country: 'Canada' },
    { title: 'Montreal', country: 'Canada' },
    { title: 'Calgary', country: 'Canada' },
    { title: 'Ottawa', country: 'Canada' },
    { title: 'London', country: 'United Kingdom' },
    { title: 'Manchester', country: 'United Kingdom' },
    { title: 'Birmingham', country: 'United Kingdom' },
    { title: 'Glasgow', country: 'United Kingdom' },
    { title: 'Liverpool', country: 'United Kingdom' },
    { title: 'Paris', country: 'France' },
    { title: 'Marseille', country: 'France' },
    { title: 'Lyon', country: 'France' },
    { title: 'Toulouse', country: 'France' },
    { title: 'Nice', country: 'France' },
    { title: 'Berlin', country: 'Germany' },
    { title: 'Hamburg', country: 'Germany' },
    { title: 'Munich', country: 'Germany' },
    { title: 'Cologne', country: 'Germany' },
    { title: 'Frankfurt', country: 'Germany' },
    { title: 'Rome', country: 'Italy' },
    { title: 'Milan', country: 'Italy' },
    { title: 'Naples', country: 'Italy' },
    { title: 'Turin', country: 'Italy' },
    { title: 'Palermo', country: 'Italy' },
    { title: 'Madrid', country: 'Spain' },
    { title: 'Barcelona', country: 'Spain' },
    { title: 'Valencia', country: 'Spain' },
    { title: 'Seville', country: 'Spain' },
    { title: 'Zaragoza', country: 'Spain' },
    { title: 'Sydney', country: 'Australia' },
    { title: 'Melbourne', country: 'Australia' },
    { title: 'Brisbane', country: 'Australia' },
    { title: 'Perth', country: 'Australia' },
    { title: 'Adelaide', country: 'Australia' },
    { title: 'Tokyo', country: 'Japan' },
    { title: 'Osaka', country: 'Japan' },
    { title: 'Kyoto', country: 'Japan' },
    { title: 'Yokohama', country: 'Japan' },
    { title: 'Sapporo', country: 'Japan' },
    { title: 'Beijing', country: 'China' },
    { title: 'Shanghai', country: 'China' },
    { title: 'Shenzhen', country: 'China' },
    { title: 'Guangzhou', country: 'China' },
    { title: 'Chengdu', country: 'China' },
    { title: 'Mumbai', country: 'India' },
    { title: 'Delhi', country: 'India' },
    { title: 'Bangalore', country: 'India' },
    { title: 'Kolkata', country: 'India' },
    { title: 'Chennai', country: 'India' },
    { title: 'São Paulo', country: 'Brazil' },
    { title: 'Rio de Janeiro', country: 'Brazil' },
    { title: 'Brasília', country: 'Brazil' },
    { title: 'Salvador', country: 'Brazil' },
    { title: 'Fortaleza', country: 'Brazil' },
    { title: 'Mexico City', country: 'Mexico' },
    { title: 'Guadalajara', country: 'Mexico' },
    { title: 'Monterrey', country: 'Mexico' },
    { title: 'Puebla', country: 'Mexico' },
    { title: 'Tijuana', country: 'Mexico' },
    { title: 'Moscow', country: 'Russia' },
    { title: 'Saint Petersburg', country: 'Russia' },
    { title: 'Novosibirsk', country: 'Russia' },
    { title: 'Yekaterinburg', country: 'Russia' },
    { title: 'Kazan', country: 'Russia' },
    { title: 'Kyiv', country: 'Ukraine' },
    { title: 'Lviv', country: 'Ukraine' },
    { title: 'Odesa', country: 'Ukraine' },
    { title: 'Kharkiv', country: 'Ukraine' },
    { title: 'Dnipro', country: 'Ukraine' },
    { title: 'Seoul', country: 'South Korea' },
    { title: 'Busan', country: 'South Korea' },
    { title: 'Incheon', country: 'South Korea' },
    { title: 'Daegu', country: 'South Korea' },
    { title: 'Daejeon', country: 'South Korea' },
    { title: 'Istanbul', country: 'Turkey' },
    { title: 'Ankara', country: 'Turkey' },
    { title: 'Izmir', country: 'Turkey' },
    { title: 'Antalya', country: 'Turkey' },
    { title: 'Bursa', country: 'Turkey' },
    { title: 'Buenos Aires', country: 'Argentina' },
    { title: 'Córdoba', country: 'Argentina' },
    { title: 'Rosario', country: 'Argentina' },
    { title: 'Mendoza', country: 'Argentina' },
    { title: 'La Plata', country: 'Argentina' },
    { title: 'Johannesburg', country: 'South Africa' },
    { title: 'Cape Town', country: 'South Africa' },
    { title: 'Durban', country: 'South Africa' },
    { title: 'Pretoria', country: 'South Africa' },
    { title: 'Port Elizabeth', country: 'South Africa' },
    { title: 'Cairo', country: 'Egypt' },
    { title: 'Alexandria', country: 'Egypt' },
    { title: 'Giza', country: 'Egypt' },
    { title: 'Shubra El Kheima', country: 'Egypt' },
    { title: 'Port Said', country: 'Egypt' },
];